name: Healthcare Agent CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff Linter
        run: |
          ruff check .

      - name: Run Pytest
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Connect To Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.WINDOWS_SSH_PRIVATE_KEY }}" > ~/.ssh/github_cd
          chmod 600 ~/.ssh/github_cd

      - name: Deploy To Windows Server
        run: |
          ssh -o BatchMode=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -T \
          -i ~/.ssh/github_cd \
          Uttam@100.81.202.58 \
          "powershell -ExecutionPolicy Bypass -File 'E:\Projects\Deployment\medical-bot-with-cicd\deploy.ps1'; exit"